export const GITHUB:string = "https://github.com/itsbibeksaini"
export const LINKEDIN:string = "https://www.linkedin.com/in/itsbibeksaini"
export const FACEBOOK:string = "https://www.facebook.com/itsbibeksaini"
export const INSTAGRM:string = "https://www.instagram.com/itsbibeksaini/"
export const RESUME:string = "assets/resume.pdf"