export {AboutMeComponent} from './about-me/about-me.component'
export {HomeComponent} from './home/home.component'
export {ProjectsComponent} from './projects/projects.component'
export {SidebarComponent} from './sidebar/sidebar.component'
export {SkillsComponent} from './skills/skills.component'
export {WorkComponent} from './work/work.component'
export {ContactMeComponent} from './contact-me/contact-me.component'